//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdventureWorks2019Entities : DbContext
    {
        public AdventureWorks2019Entities()
            : base("name=AdventureWorks2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetAllProductCategoriesAndSubcategories_Result> GetAllProductCategoriesAndSubcategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProductCategoriesAndSubcategories_Result>("GetAllProductCategoriesAndSubcategories");
        }
    
        public virtual ObjectResult<GetProductReviews_Result> GetProductReviews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductReviews_Result>("GetProductReviews");
        }
    
        public virtual ObjectResult<GetProductSalesByYear_Result> GetProductSalesByYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductSalesByYear_Result>("GetProductSalesByYear");
        }
    
        public virtual ObjectResult<LocationDelete_Result> LocationDelete(Nullable<int> lOCATIONID)
        {
            var lOCATIONIDParameter = lOCATIONID.HasValue ?
                new ObjectParameter("LOCATIONID", lOCATIONID) :
                new ObjectParameter("LOCATIONID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationDelete_Result>("LocationDelete", lOCATIONIDParameter);
        }
    
        public virtual ObjectResult<LocationGetAll_Result> LocationGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationGetAll_Result>("LocationGetAll");
        }
    
        public virtual ObjectResult<LocationSave_Result> LocationSave(Nullable<int> lOCATIONID, string nAME, Nullable<decimal> cOSTRATE, Nullable<decimal> aVAILABILITY)
        {
            var lOCATIONIDParameter = lOCATIONID.HasValue ?
                new ObjectParameter("LOCATIONID", lOCATIONID) :
                new ObjectParameter("LOCATIONID", typeof(int));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var cOSTRATEParameter = cOSTRATE.HasValue ?
                new ObjectParameter("COSTRATE", cOSTRATE) :
                new ObjectParameter("COSTRATE", typeof(decimal));
    
            var aVAILABILITYParameter = aVAILABILITY.HasValue ?
                new ObjectParameter("AVAILABILITY", aVAILABILITY) :
                new ObjectParameter("AVAILABILITY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationSave_Result>("LocationSave", lOCATIONIDParameter, nAMEParameter, cOSTRATEParameter, aVAILABILITYParameter);
        }
    
        public virtual ObjectResult<CreditCardDelete_Result> CreditCardDelete(Nullable<int> cREDITCARDID)
        {
            var cREDITCARDIDParameter = cREDITCARDID.HasValue ?
                new ObjectParameter("CREDITCARDID", cREDITCARDID) :
                new ObjectParameter("CREDITCARDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreditCardDelete_Result>("CreditCardDelete", cREDITCARDIDParameter);
        }
    
        public virtual ObjectResult<CreditCardGetAll_Result> CreditCardGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreditCardGetAll_Result>("CreditCardGetAll");
        }
    
        public virtual ObjectResult<CreditCardSave_Result> CreditCardSave(Nullable<int> creditCardId, string cardType, string cardNumber, Nullable<int> expMonth, Nullable<int> expYear)
        {
            var creditCardIdParameter = creditCardId.HasValue ?
                new ObjectParameter("CreditCardId", creditCardId) :
                new ObjectParameter("CreditCardId", typeof(int));
    
            var cardTypeParameter = cardType != null ?
                new ObjectParameter("CardType", cardType) :
                new ObjectParameter("CardType", typeof(string));
    
            var cardNumberParameter = cardNumber != null ?
                new ObjectParameter("CardNumber", cardNumber) :
                new ObjectParameter("CardNumber", typeof(string));
    
            var expMonthParameter = expMonth.HasValue ?
                new ObjectParameter("ExpMonth", expMonth) :
                new ObjectParameter("ExpMonth", typeof(int));
    
            var expYearParameter = expYear.HasValue ?
                new ObjectParameter("ExpYear", expYear) :
                new ObjectParameter("ExpYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreditCardSave_Result>("CreditCardSave", creditCardIdParameter, cardTypeParameter, cardNumberParameter, expMonthParameter, expYearParameter);
        }
    }
}
