//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWApp.AWService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllProductCategoriesAndSubcategories_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class GetAllProductCategoriesAndSubcategories_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubcategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubcategoryName {
            get {
                return this.SubcategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubcategoryNameField, value) != true)) {
                    this.SubcategoryNameField = value;
                    this.RaisePropertyChanged("SubcategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductReviews_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class GetProductReviews_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductReviewIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReviewDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductModelID {
            get {
                return this.ProductModelIDField;
            }
            set {
                if ((this.ProductModelIDField.Equals(value) != true)) {
                    this.ProductModelIDField = value;
                    this.RaisePropertyChanged("ProductModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductReviewID {
            get {
                return this.ProductReviewIDField;
            }
            set {
                if ((this.ProductReviewIDField.Equals(value) != true)) {
                    this.ProductReviewIDField = value;
                    this.RaisePropertyChanged("ProductReviewID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReviewDate {
            get {
                return this.ReviewDateField;
            }
            set {
                if ((this.ReviewDateField.Equals(value) != true)) {
                    this.ReviewDateField = value;
                    this.RaisePropertyChanged("ReviewDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductSalesByYear_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class GetProductSalesByYear_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SalesYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalSalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SalesYear {
            get {
                return this.SalesYearField;
            }
            set {
                if ((this.SalesYearField.Equals(value) != true)) {
                    this.SalesYearField = value;
                    this.RaisePropertyChanged("SalesYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalSales {
            get {
                return this.TotalSalesField;
            }
            set {
                if ((this.TotalSalesField.Equals(value) != true)) {
                    this.TotalSalesField = value;
                    this.RaisePropertyChanged("TotalSales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardGetAll_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class CreditCardGetAll_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditCardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ExpMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExpYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditCardID {
            get {
                return this.CreditCardIDField;
            }
            set {
                if ((this.CreditCardIDField.Equals(value) != true)) {
                    this.CreditCardIDField = value;
                    this.RaisePropertyChanged("CreditCardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ExpMonth {
            get {
                return this.ExpMonthField;
            }
            set {
                if ((this.ExpMonthField.Equals(value) != true)) {
                    this.ExpMonthField = value;
                    this.RaisePropertyChanged("ExpMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExpYear {
            get {
                return this.ExpYearField;
            }
            set {
                if ((this.ExpYearField.Equals(value) != true)) {
                    this.ExpYearField = value;
                    this.RaisePropertyChanged("ExpYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardSave_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class CreditCardSave_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardDelete_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class CreditCardDelete_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENSAJEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAJE {
            get {
                return this.MENSAJEField;
            }
            set {
                if ((object.ReferenceEquals(this.MENSAJEField, value) != true)) {
                    this.MENSAJEField = value;
                    this.RaisePropertyChanged("MENSAJE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationGetAll_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class LocationGetAll_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short LocationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Availability {
            get {
                return this.AvailabilityField;
            }
            set {
                if ((this.AvailabilityField.Equals(value) != true)) {
                    this.AvailabilityField = value;
                    this.RaisePropertyChanged("Availability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostRate {
            get {
                return this.CostRateField;
            }
            set {
                if ((this.CostRateField.Equals(value) != true)) {
                    this.CostRateField = value;
                    this.RaisePropertyChanged("CostRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short LocationID {
            get {
                return this.LocationIDField;
            }
            set {
                if ((this.LocationIDField.Equals(value) != true)) {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationSave_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class LocationSave_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationDelete_Result", Namespace="http://schemas.datacontract.org/2004/07/AWService.Data")]
    [System.SerializableAttribute()]
    public partial class LocationDelete_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENSAJEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAJE {
            get {
                return this.MENSAJEField;
            }
            set {
                if ((object.ReferenceEquals(this.MENSAJEField, value) != true)) {
                    this.MENSAJEField = value;
                    this.RaisePropertyChanged("MENSAJE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AWService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProductCategoriesAndSubcategoriesResult", ReplyAction="http://tempuri.org/IService1/ListaProductCategoriesAndSubcategoriesResultResponse" +
            "")]
        AWApp.AWService.GetAllProductCategoriesAndSubcategories_Result[] ListaProductCategoriesAndSubcategoriesResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProductCategoriesAndSubcategoriesResult", ReplyAction="http://tempuri.org/IService1/ListaProductCategoriesAndSubcategoriesResultResponse" +
            "")]
        System.Threading.Tasks.Task<AWApp.AWService.GetAllProductCategoriesAndSubcategories_Result[]> ListaProductCategoriesAndSubcategoriesResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProductReviewsResult", ReplyAction="http://tempuri.org/IService1/ListaProductReviewsResultResponse")]
        AWApp.AWService.GetProductReviews_Result[] ListaProductReviewsResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProductReviewsResult", ReplyAction="http://tempuri.org/IService1/ListaProductReviewsResultResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.GetProductReviews_Result[]> ListaProductReviewsResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProductSalesByYearResult", ReplyAction="http://tempuri.org/IService1/ListaProductSalesByYearResultResponse")]
        AWApp.AWService.GetProductSalesByYear_Result[] ListaProductSalesByYearResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProductSalesByYearResult", ReplyAction="http://tempuri.org/IService1/ListaProductSalesByYearResultResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.GetProductSalesByYear_Result[]> ListaProductSalesByYearResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCreditCardGetAllResult", ReplyAction="http://tempuri.org/IService1/ListaCreditCardGetAllResultResponse")]
        AWApp.AWService.CreditCardGetAll_Result[] ListaCreditCardGetAllResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCreditCardGetAllResult", ReplyAction="http://tempuri.org/IService1/ListaCreditCardGetAllResultResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.CreditCardGetAll_Result[]> ListaCreditCardGetAllResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardSave", ReplyAction="http://tempuri.org/IService1/CreditCardSaveResponse")]
        AWApp.AWService.CreditCardSave_Result CreditCardSave(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardSave", ReplyAction="http://tempuri.org/IService1/CreditCardSaveResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.CreditCardSave_Result> CreditCardSaveAsync(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardDelete", ReplyAction="http://tempuri.org/IService1/CreditCardDeleteResponse")]
        AWApp.AWService.CreditCardDelete_Result CreditCardDelete(int CreditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardDelete", ReplyAction="http://tempuri.org/IService1/CreditCardDeleteResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.CreditCardDelete_Result> CreditCardDeleteAsync(int CreditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaLocationGetAllResult", ReplyAction="http://tempuri.org/IService1/ListaLocationGetAllResultResponse")]
        AWApp.AWService.LocationGetAll_Result[] ListaLocationGetAllResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaLocationGetAllResult", ReplyAction="http://tempuri.org/IService1/ListaLocationGetAllResultResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.LocationGetAll_Result[]> ListaLocationGetAllResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LocationSave", ReplyAction="http://tempuri.org/IService1/LocationSaveResponse")]
        AWApp.AWService.LocationSave_Result LocationSave(int LocationId, string Name, decimal CostRate, decimal Availability);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LocationSave", ReplyAction="http://tempuri.org/IService1/LocationSaveResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.LocationSave_Result> LocationSaveAsync(int LocationId, string Name, decimal CostRate, decimal Availability);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LocationDelete", ReplyAction="http://tempuri.org/IService1/LocationDeleteResponse")]
        AWApp.AWService.LocationDelete_Result LocationDelete(int LocationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LocationDelete", ReplyAction="http://tempuri.org/IService1/LocationDeleteResponse")]
        System.Threading.Tasks.Task<AWApp.AWService.LocationDelete_Result> LocationDeleteAsync(int LocationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AWApp.AWService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AWApp.AWService.IService1>, AWApp.AWService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AWApp.AWService.GetAllProductCategoriesAndSubcategories_Result[] ListaProductCategoriesAndSubcategoriesResult() {
            return base.Channel.ListaProductCategoriesAndSubcategoriesResult();
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.GetAllProductCategoriesAndSubcategories_Result[]> ListaProductCategoriesAndSubcategoriesResultAsync() {
            return base.Channel.ListaProductCategoriesAndSubcategoriesResultAsync();
        }
        
        public AWApp.AWService.GetProductReviews_Result[] ListaProductReviewsResult() {
            return base.Channel.ListaProductReviewsResult();
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.GetProductReviews_Result[]> ListaProductReviewsResultAsync() {
            return base.Channel.ListaProductReviewsResultAsync();
        }
        
        public AWApp.AWService.GetProductSalesByYear_Result[] ListaProductSalesByYearResult() {
            return base.Channel.ListaProductSalesByYearResult();
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.GetProductSalesByYear_Result[]> ListaProductSalesByYearResultAsync() {
            return base.Channel.ListaProductSalesByYearResultAsync();
        }
        
        public AWApp.AWService.CreditCardGetAll_Result[] ListaCreditCardGetAllResult() {
            return base.Channel.ListaCreditCardGetAllResult();
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.CreditCardGetAll_Result[]> ListaCreditCardGetAllResultAsync() {
            return base.Channel.ListaCreditCardGetAllResultAsync();
        }
        
        public AWApp.AWService.CreditCardSave_Result CreditCardSave(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear) {
            return base.Channel.CreditCardSave(CreditCardId, CardType, CardNumber, ExpMonth, ExpYear);
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.CreditCardSave_Result> CreditCardSaveAsync(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear) {
            return base.Channel.CreditCardSaveAsync(CreditCardId, CardType, CardNumber, ExpMonth, ExpYear);
        }
        
        public AWApp.AWService.CreditCardDelete_Result CreditCardDelete(int CreditCardId) {
            return base.Channel.CreditCardDelete(CreditCardId);
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.CreditCardDelete_Result> CreditCardDeleteAsync(int CreditCardId) {
            return base.Channel.CreditCardDeleteAsync(CreditCardId);
        }
        
        public AWApp.AWService.LocationGetAll_Result[] ListaLocationGetAllResult() {
            return base.Channel.ListaLocationGetAllResult();
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.LocationGetAll_Result[]> ListaLocationGetAllResultAsync() {
            return base.Channel.ListaLocationGetAllResultAsync();
        }
        
        public AWApp.AWService.LocationSave_Result LocationSave(int LocationId, string Name, decimal CostRate, decimal Availability) {
            return base.Channel.LocationSave(LocationId, Name, CostRate, Availability);
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.LocationSave_Result> LocationSaveAsync(int LocationId, string Name, decimal CostRate, decimal Availability) {
            return base.Channel.LocationSaveAsync(LocationId, Name, CostRate, Availability);
        }
        
        public AWApp.AWService.LocationDelete_Result LocationDelete(int LocationId) {
            return base.Channel.LocationDelete(LocationId);
        }
        
        public System.Threading.Tasks.Task<AWApp.AWService.LocationDelete_Result> LocationDeleteAsync(int LocationId) {
            return base.Channel.LocationDeleteAsync(LocationId);
        }
    }
}
